### ISSUE TITLE
Question about IP address

### ISSUE THREAD

**Issue by 7mguest** [adnapPanda/WIZLights#3]
Sorry to bother but, but I was wondering what Ip address I need for this to work, as i've tried using the IP address for the lights strips use but that doesn't work.

**Comment by adnapPanda** [comment]
It should just be the ip address of the lights, but tbh I didn't even know that they make light strips. Did you use the WIZ Lights app to set them up and how are you getting their IP address? Are you on the same wifi/ethernet as the lights? Are the lights turned on when you are playing osrs?

**Comment by 7mguest** [comment]
I used the wiz android app to set them up and made sure to have the lights on during play,  I got the IP address for the light strips from my router settings as it shows everything connected to the network, and i checked my lights settings in the app and it game me the same ip. So I'm just guessing that its a fault in the lights strips themselves

**Comment by adnapPanda** [comment]
Sounds like you are doing everything correctly. Maybe the light strips take different commands than the light bulbs, not sure on this. If you would like I could add you on discord and I could send you some python/java commands you can use standalone to see if your light strips change color

**Comment by 7mguest** [comment]
Never mind I reset my computer for an update and it got fix, must have been something running that was disrupting the process. Thanks for the help and sorry for bothering you.
